### PR TITLE
Add react roles

### LINKED ISSUE #5: Make more reaction roles
https://gist.github.com/asportnoy/c0af9bce924f707909ff439d8b694ed0

### PR DESCRIPTION
**Pull request by asportnoy**
This adds support for multiple react roles as well as new modes. Config is explained at the top of the file.

Current modes available:
NORMAL: add role on reaction add, remove role on reaction remove
VERIFY: add role and remove reaction on reaction add. Do not allow role removal.
REVERSE: remove role on reaction add, add role on reaction remove
REVERSE_VERIFY: remove role and reaction on reaction remove. Do not allow role addition.
TOGGLE: toggle role and remove reaction on reaction add.

Code can be easily adapted to add more modes and other functionality.

Closes #5

### CODE REVIEW

**Comment by asportnoy** [comment]
@LPB8479 bumping this

**Comment by LPB8479** [comment]
> @LPB8479 bumping this

Haven't forgotten. I want to go through it to make sure I understand it (since I'm still learning myself) before integrating it, but finals are a pain in the ass. Hoping to get it done in the next week or so.

**Comment by LPB8479** [comment]
@asportnoy Looks fine but there's a few changes I'd like to make (either of us could do it ig): In the config file it looks like you kept the config as a const in addition to making it an interface (I'm guessing this wasn't intentional). I'm also thinking it would make more sense to have all config relating to rrs be on the rr file, so that multiple different rrs can be used.

Also, it looks like you added `typeof` to `  slashCommands: discord.interactions.commands`. Was this intentional?

**Comment by asportnoy** [comment]
The `interface` is a type definition for the `const`. The name should be fine since one is a type and one is a value, but if not you can change it to an uppercase C.

The `typeof` is intentional since it's a type definition.

**Comment by LPB8479** [comment]
I'm going to close this pr and update the code manually since changes to the config file in the `main` branch are preventing me from merging the pr normally and I barely know what I'm doing with Git to fix it properly. Nevertheless, thanks for the contribution!

**Pull request closed without merging**
